extends RefCounted

const PartyStateScript = preload("res://scripts/domain/party_state.gd")
const GameStateScript = preload("res://scripts/core/game_state.gd")

func run(assertions) -> void:
	var party = PartyStateScript.new()
	party.add_member("hero_yun")
	party.add_member("hero_yun")
	assertions.assert_eq(party.members.size(), 1, "重复 add_member 不应重复入队")
	assertions.assert_eq(party.get_formation_order(), ["hero_yun"], "默认编队应包含主角")

	party.add_member("qingshanke")
	party.add_member("porter_chen")
	assertions.assert_eq(party.get_formation_order(), ["hero_yun", "qingshanke", "porter_chen"], "新队友应追加到默认编队末尾")
	party.set_formation_order(["qingshanke", "hero_yun", "missing_actor", "qingshanke"])
	assertions.assert_eq(party.get_formation_order(), ["hero_yun", "qingshanke", "porter_chen"], "编队应过滤无效成员、去重并保持主角首位")
	party.move_formation_member("qingshanke", -1)
	assertions.assert_eq(party.get_formation_order(), ["hero_yun", "qingshanke", "porter_chen"], "队友不应移动到主角之前")
	party.move_formation_member("porter_chen", -1)
	assertions.assert_eq(party.get_formation_order(), ["hero_yun", "porter_chen", "qingshanke"], "非主角队友应可上移")
	party.move_formation_member("porter_chen", 1)
	assertions.assert_eq(party.get_formation_order(), ["hero_yun", "qingshanke", "porter_chen"], "非主角队友应可下移")
	assertions.assert_eq(party.get_deployable_members(2), ["hero_yun", "qingshanke"], "出战成员应按编队顺序和上限截断")
	assertions.assert_eq(party.get_deployable_members(0), [], "出战上限小于等于 0 时应为空")

	party.set_member_status("hero_yun", {"hp": 90, "mp": 7})
	assertions.assert_eq(party.get_member_status("hero_yun").get("hp", 0), 90, "应保存成员 HP")
	assertions.assert_eq(party.get_member_status("hero_yun").get("mp", 0), 7, "应保存成员 MP")
	assertions.assert_eq(party.get_member_status("hero_yun").get("level", 0), 1, "未传等级时应默认为 1 级")
	assertions.assert_eq(party.get_member_status("hero_yun").get("exp", -1), 0, "未传经验时应默认为 0")
	assertions.assert_eq(party.get_member_status("hero_yun").get("total_exp", -1), 0, "未传累计经验时应默认为 0")

	party.set_member_status("hero_yun", {"level": 3, "exp": 12, "total_exp": 92})
	var hero_status = party.get_member_status("hero_yun")
	assertions.assert_eq(hero_status.get("hp", 0), 90, "更新成长字段时应保留成员 HP")
	assertions.assert_eq(hero_status.get("mp", 0), 7, "更新成长字段时应保留成员 MP")
	assertions.assert_eq(hero_status.get("level", 0), 3, "应保存成员等级")
	assertions.assert_eq(hero_status.get("exp", -1), 12, "应保存当前等级经验")
	assertions.assert_eq(hero_status.get("total_exp", -1), 92, "应保存累计经验")

	party.add_item("iron_sword", 1)
	party.set_equipment("hero_yun", "weapon", "iron_sword")
	assertions.assert_eq(party.get_equipped_item("hero_yun", "weapon"), "iron_sword", "应读取装备槽物品")
	assertions.assert_eq(party.count_equipped_item("iron_sword"), 1, "应统计装备占用数量")
	party.clear_equipment("hero_yun", "weapon")
	assertions.assert_eq(party.get_equipped_item("hero_yun", "weapon"), "", "卸下装备后槽位应为空")

	var data = party.to_dictionary()
	var restored = PartyStateScript.new()
	restored.from_dictionary(data)
	assertions.assert_eq(restored.get_member_status("hero_yun").get("hp", 0), 90, "成员状态应可序列化恢复")
	assertions.assert_eq(restored.get_member_status("hero_yun").get("mp", 0), 7, "成员内力应可序列化恢复")
	assertions.assert_eq(restored.get_member_status("hero_yun").get("level", 0), 3, "成员等级应可序列化恢复")
	assertions.assert_eq(restored.get_member_status("hero_yun").get("exp", -1), 12, "成员当前等级经验应可序列化恢复")
	assertions.assert_eq(restored.get_member_status("hero_yun").get("total_exp", -1), 92, "成员累计经验应可序列化恢复")
	assertions.assert_eq(restored.get_equipped_item("hero_yun", "weapon"), "", "空装备槽不应恢复出旧装备")
	assertions.assert_eq(restored.get_formation_order(), ["hero_yun", "qingshanke", "porter_chen"], "默认编队应可序列化恢复")

	var old_save = PartyStateScript.new()
	old_save.from_dictionary({"members": ["qingshanke", "hero_yun"], "inventory": {"herb_small": 1}, "coins": 5})
	assertions.assert_eq(old_save.equipment.size(), 0, "旧存档缺 equipment 时应默认为空")
	assertions.assert_eq(old_save.member_status.size(), 0, "旧存档缺 member_status 时应默认为空")
	assertions.assert_eq(old_save.get_formation_order(), ["hero_yun", "qingshanke"], "旧存档缺 formation_order 时应生成主角首位的默认编队")
	old_save.from_dictionary({"members": ["hero_yun"], "member_status": {"hero_yun": {"hp": 50, "mp": 4}}})
	var old_status = old_save.get_member_status("hero_yun")
	assertions.assert_eq(old_status.get("level", 0), 1, "旧成员状态缺等级时应默认为 1 级")
	assertions.assert_eq(old_status.get("exp", -1), 0, "旧成员状态缺经验时应默认为 0")
	assertions.assert_eq(old_status.get("total_exp", -1), 0, "旧成员状态缺累计经验时应默认为 0")

	var state = GameStateScript.new()
	state.start_new_game()
	assertions.assert_true(state.party.has_member("hero_yun"), "新游戏应包含主角")
	assertions.assert_eq(state.party.get_member_status("hero_yun").get("hp", 0), state.hero_hp, "新游戏应初始化主角成员 HP")
	assertions.assert_eq(state.party.get_member_status("hero_yun").get("mp", 0), state.hero_cur_mp, "新游戏应初始化主角成员 MP")
	state.free()